// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0B9o7WLCTgEHecwpdPiAmYh4JVN2AfEE',
    appId: '1:195054877306:web:6f79f6a4a2628dcc6619c3',
    messagingSenderId: '195054877306',
    projectId: 'tottori-28f47',
    authDomain: 'tottori-28f47.firebaseapp.com',
    storageBucket: 'tottori-28f47.appspot.com',
    measurementId: 'G-18005SJ043',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-mjTxBQ87e6EfIMScxcevufxP11UukMs',
    appId: '1:195054877306:android:b678959a93f5b64c6619c3',
    messagingSenderId: '195054877306',
    projectId: 'tottori-28f47',
    storageBucket: 'tottori-28f47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGJiQ1haOw861QR8gIDz7wFYIBcS9Jy9A',
    appId: '1:195054877306:ios:9ee806396db0535a6619c3',
    messagingSenderId: '195054877306',
    projectId: 'tottori-28f47',
    storageBucket: 'tottori-28f47.appspot.com',
    iosClientId: '195054877306-buj46o2m9oggo0cuql0pqvnanntvac4d.apps.googleusercontent.com',
    iosBundleId: 'com.larswust.tottori',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGJiQ1haOw861QR8gIDz7wFYIBcS9Jy9A',
    appId: '1:195054877306:ios:2cebca3d0caa23456619c3',
    messagingSenderId: '195054877306',
    projectId: 'tottori-28f47',
    storageBucket: 'tottori-28f47.appspot.com',
    iosClientId: '195054877306-gv374vqsvc79p5ct75rokaop7gt9qpfs.apps.googleusercontent.com',
    iosBundleId: 'com.example.tottori',
  );
}
